import { detectEntryPoints } from "./detectors/entry-points.js";
import { buildOverview } from "./detectors/overview.js";
import { detectProjectType } from "./detectors/project-type.js";
import {
    detectReusableSystem,
    detectSharedUi,
    detectUtilityDirs,
} from "./detectors/reusable-system.js";
import { detectRiskAreas } from "./detectors/risk-areas.js";
import {
    CONTEXT_AI_PATH,
    CONTEXT_DIR,
    CONTEXT_INDEX_ENTRYPOINTS_PATH,
    CONTEXT_INDEX_FILE_GROUPS_PATH,
    CONTEXT_INDEX_FILES_PATH,
    CONTEXT_INDEX_SUMMARY_PATH,
    CONTEXT_INDEX_SYMBOLS_PATH,
    CONTEXT_PROJECT_MD_PATH,
    CONTEXT_SYSTEM_OVERVIEW_PATH,
    CONTEXT_TASKS_PATH,
} from "./constants.js";
import { getContextStatus } from "./context.js";
import {
    getClosestStructurePath,
    detectStructure,
    getStructureDescription,
} from "./detectors/structure.js";
import { exists, isDirectory, readJson } from "./fs-utils.js";
import { detectPackageMetadata, detectTechStack } from "./package-utils.js";
import { buildTaskMap, updateProjectIndex } from "./indexers/project-index.js";
import {
    generateSystemOverviewContent,
    getSystemOverviewUpdate,
    updateSystemOverview,
} from "./system-overview.js";
import { getTaskConsistencyWarnings } from "./task-files.js";
import { getProjectMdUpdate, updateProjectMd } from "./writers/project-md.js";

function formatDescriptiveList(items) {
    return items.map((item) =>
        item.description ? `- ${item.label} -> ${item.description}` : `- ${item.label}`,
    );
}

function extractReferencedDirectories(lines) {
    const referencedDirs = new Set();
    const pathMatches = lines.flatMap(
        (line) => line.match(/(?:\.[A-Za-z0-9_-]+|[A-Za-z0-9_-]+)(?:\/[A-Za-z0-9_.-]+)+\/?/g) || [],
    );

    for (const match of pathMatches) {
        const normalized = match.replace(/`/g, "").replace(/\/+$/, "");
        const mappedStructurePath = getClosestStructurePath(normalized);

        if (mappedStructurePath && exists(mappedStructurePath)) {
            referencedDirs.add(mappedStructurePath);
            continue;
        }

        if (isDirectory(normalized)) {
            referencedDirs.add(normalized);
            continue;
        }

        const lastSlashIndex = normalized.lastIndexOf("/");
        if (lastSlashIndex === -1) {
            continue;
        }

        const parentDir = normalized.slice(0, lastSlashIndex);
        const mappedParentPath = getClosestStructurePath(parentDir);

        if (mappedParentPath && exists(mappedParentPath)) {
            referencedDirs.add(mappedParentPath);
            continue;
        }

        if (parentDir && isDirectory(parentDir)) {
            referencedDirs.add(parentDir);
        }
    }

    return [...referencedDirs];
}

function mergeStructureWithReferences(structure, reusableSystem, risks) {
    const structureByLabel = new Map(structure.map((item) => [item.label, item]));
    const referencedDirs = extractReferencedDirectories([
        ...reusableSystem.sections.flatMap((section) => section.items),
        ...risks,
    ]);

    for (const dir of referencedDirs) {
        const label = `${dir}/`;

        if (structureByLabel.has(label)) {
            continue;
        }

        structureByLabel.set(label, {
            label,
            description:
                getStructureDescription(dir) ||
                "referenced project directory with shared implementation significance",
        });
    }

    return [...structureByLabel.values()];
}

function buildProjectScanData() {
    const projectType = detectProjectType();
    const techStack = detectTechStack(projectType);
    const packageMetadata = detectPackageMetadata();
    const sharedUi = detectSharedUi();
    const utilityDirs = detectUtilityDirs();
    const reusableSystem = detectReusableSystem(
        projectType,
        sharedUi,
        utilityDirs,
    );
    const structure = detectStructure(projectType);
    const risks = detectRiskAreas(projectType, structure, sharedUi);
    const mergedStructure = mergeStructureWithReferences(
        structure,
        reusableSystem,
        risks,
    );
    const entryPoints = detectEntryPoints(projectType);
    const overview = buildOverview(projectType, techStack);

    return {
        projectType,
        techStack,
        packageMetadata,
        reusableSystem,
        risks,
        mergedStructure,
        entryPoints,
        overview,
    };
}

export function generateProjectMdContent(scanData = buildProjectScanData()) {
    const {
        projectType,
        techStack,
        packageMetadata,
        reusableSystem,
        risks,
        mergedStructure,
        entryPoints,
        overview,
    } = scanData;

    const lines = [
        "This section is automatically generated by `repo-context-kit scan`.",
        "Do not edit manually.",
        "",
        "## Project Type",
        `- ${projectType}`,
        "",
        "## Overview",
        ...overview,
        "",
        "## Tech Stack",
    ];

    if (techStack.length === 0) {
        lines.push("- Not clearly detected");
    } else {
        lines.push(...techStack.map((item) => `- ${item}`));
    }

    lines.push("", "## Package Metadata");
    if (!packageMetadata) {
        lines.push("- package.json not found");
    } else {
        if (packageMetadata.name) {
            lines.push(`- name: ${packageMetadata.name}`);
        }
        if (packageMetadata.version) {
            lines.push(`- version: ${packageMetadata.version}`);
        }
        if (packageMetadata.type) {
            lines.push(`- module type: ${packageMetadata.type}`);
        }
        if (packageMetadata.license) {
            lines.push(`- license: ${packageMetadata.license}`);
        }
        if (packageMetadata.packageManager) {
            lines.push(`- package manager: ${packageMetadata.packageManager}`);
        }

        if (packageMetadata.bin.length > 0) {
            lines.push("- bin:");
            for (const binEntry of packageMetadata.bin) {
                lines.push(`  - ${binEntry.name} -> ${binEntry.path}`);
            }
        }

        if (packageMetadata.scripts.length > 0) {
            lines.push("- scripts:");
            for (const script of packageMetadata.scripts) {
                lines.push(`  - ${script.name}: ${script.command}`);
            }
        }
    }

    lines.push(
        "",
        "## AI Development Notes",
        "- This is an npm CLI tool",
        "- Entry point: bin/cli.js",
        "- Template files are copied into user projects during init",
        "- template/ paths are runtime template sources; do not rewrite them as generated output paths",
        `- .claude/skills and ${CONTEXT_DIR}/tests are generated in user projects when present in the template`,
        "- Do not modify generated files unless explicitly required",
        "- Preserve package manager (npm/yarn/pnpm)",
        "- Follow existing file structure when adding new features",
    );

    lines.push("", "## Structure Overview");
    if (mergedStructure.length === 0) {
        lines.push("- No standard project structure detected");
    } else {
        lines.push(...formatDescriptiveList(mergedStructure));
    }

    lines.push("", "## Entry Points");
    if (entryPoints.length === 0) {
        lines.push("- No common entry files detected");
    } else {
        lines.push(...formatDescriptiveList(entryPoints));
    }

    lines.push("", "## Reusable System");
    for (const section of reusableSystem.sections) {
        lines.push(`### ${section.title}`);
        lines.push(...section.items.map((item) => `- ${item}`));
        lines.push("");
    }

    if (lines[lines.length - 1] === "") {
        lines.pop();
    }

    lines.push("", "## Risk Areas");
    if (risks.length === 0) {
        lines.push("- No obvious shared-risk areas detected");
    } else {
        lines.push(...risks.map((risk) => `- ${risk}`));
    }

    lines.push(
        "",
        "## Project Notes",
        "- Reuse existing structures before creating new ones",
        "- Treat shared modules cautiously and preserve backward compatibility",
        "- Keep changes minimal and localized unless the task explicitly requires broader refactoring",
    );

    return lines.join("\n");
}

function getUpdatedIndexFiles(indexUpdate) {
    const updatedFiles = [];

    if (indexUpdate.aiChanged) {
        updatedFiles.push(CONTEXT_AI_PATH);
    }
    if (indexUpdate.filesChanged) {
        updatedFiles.push(CONTEXT_INDEX_FILES_PATH);
    }
    if (indexUpdate.symbolsChanged) {
        updatedFiles.push(CONTEXT_INDEX_SYMBOLS_PATH);
    }
    if (indexUpdate.fileGroupsChanged) {
        updatedFiles.push(CONTEXT_INDEX_FILE_GROUPS_PATH);
    }
    if (indexUpdate.entrypointsChanged) {
        updatedFiles.push(CONTEXT_INDEX_ENTRYPOINTS_PATH);
    }
    if (indexUpdate.summaryChanged) {
        updatedFiles.push(CONTEXT_INDEX_SUMMARY_PATH);
    }
    if (indexUpdate.tasksChanged) {
        updatedFiles.push(CONTEXT_TASKS_PATH);
    }

    return updatedFiles;
}

function createScanResult(update, scanData, updatedFiles = [], warnings = []) {
    return {
        changed: update.changed,
        updatedFiles,
        warnings,
        project: {
            type: scanData.projectType,
            entryPoints: scanData.entryPoints.map((entryPoint) => entryPoint.label),
        },
    };
}

function printChanges(updatedFiles) {
    console.log("Changes:");

    if (updatedFiles.length === 0) {
        console.log("* No changes");
        return;
    }

    for (const filePath of updatedFiles) {
        console.log(`* Updated ${filePath}`);
    }
}

function printDefaultScanResult(result) {
    console.log("\u2714 Project scan completed");
    console.log("");
    printChanges(result.updatedFiles);
    console.log("");
    console.log("Summary:");
    console.log(`* Project type: ${result.project.type}`);
    console.log(
        `* Entry points: ${
            result.project.entryPoints.length > 0
                ? result.project.entryPoints.join(", ")
                : "None detected"
        }`,
    );
    printWarnings(result.warnings);
}

function printAutoScanResult(result) {
    console.log("\u2714 Project scan completed");
    console.log("");
    printChanges(result.updatedFiles);
    console.log("");
    console.log("Mode:");
    console.log("* auto");
    printWarnings(result.warnings);
}

function printWarnings(warnings = []) {
    if (warnings.length === 0) {
        return;
    }

    console.log("");
    console.log("Warnings:");
    for (const warning of warnings) {
        console.log(`* ${warning}`);
    }
}

function combineCheckUpdates(projectUpdate, systemOverviewUpdate, warnings) {
    const taskMapChanged =
        JSON.stringify(readJson(CONTEXT_TASKS_PATH) ?? null) !==
        JSON.stringify(buildTaskMap());

    return {
        changed:
            projectUpdate.changed ||
            systemOverviewUpdate.changed ||
            taskMapChanged ||
            warnings.length > 0,
        skipped: projectUpdate.skipped,
        projectChanged: projectUpdate.changed,
        systemOverviewChanged: systemOverviewUpdate.changed,
        taskMapChanged,
        taskRegistryChanged: warnings.length > 0,
    };
}

function printCheckResult(update) {
    if (update.skipped) {
        console.log("\u2716 Project context cannot be checked");
        console.log("");
        console.log("Reason:");
        console.log(`* AUTO-GENERATED markers not found in ${CONTEXT_PROJECT_MD_PATH}`);
        console.log("");
        console.log("Next:");
        console.log("* Run 'repo-context-kit scan' to regenerate.");
        return;
    }

    if (!update.changed) {
        console.log("\u2714 Project context is up to date");
        console.log("");
        console.log("Checked:");
        console.log(`* ${CONTEXT_PROJECT_MD_PATH} AUTO-GENERATED section`);
        console.log(`* ${CONTEXT_SYSTEM_OVERVIEW_PATH}`);
        return;
    }

    console.log("\u2716 Project context is outdated");
    console.log("");
    console.log("Changes:");
    if (update.projectChanged) {
        console.log(`* ${CONTEXT_PROJECT_MD_PATH} generated section is out of date`);
    }
    if (update.systemOverviewChanged) {
        console.log(`* ${CONTEXT_SYSTEM_OVERVIEW_PATH} is missing or out of date`);
    }
    if (update.taskMapChanged) {
        console.log(`* ${CONTEXT_TASKS_PATH} is missing or out of date`);
    }
    if (update.taskRegistryChanged) {
        console.log("* task registry and task files are inconsistent");
    }
    console.log("");
    console.log("Next:");
    console.log("* Run 'repo-context-kit scan' to update.");
}

function printSkippedUpdateResult() {
    console.log("\u2716 Project scan cannot update project context");
    console.log("");
    console.log("Reason:");
    console.log(`* AUTO-GENERATED markers not found in ${CONTEXT_PROJECT_MD_PATH}`);
    console.log("");
    console.log("Next:");
    console.log(`* Add AUTO-GENERATED markers or regenerate ${CONTEXT_PROJECT_MD_PATH}.`);
}

function printContextStatusError(status) {
    if (status.reason === "not-initialized") {
        console.log("\u2716 Project not initialized");
        console.log(`Missing: ${CONTEXT_DIR}/`);
        console.log("Run: repo-context-kit init");
        return;
    }

    console.log("\u2716 Project context is incomplete");
    console.log("Run: repo-context-kit scan --auto");
}

function updateProjectIndexSafe() {
    try {
        return updateProjectIndex();
    } catch (error) {
        console.warn(`Warning: Project index generation failed: ${error.message}`);
        return {
            aiChanged: false,
            filesChanged: false,
            symbolsChanged: false,
            fileGroupsChanged: false,
            entrypointsChanged: false,
            summaryChanged: false,
            tasksChanged: false,
        };
    }
}

export async function runScan(options = {}) {
    const mode = options.mode || "normal";
    const contextStatus = getContextStatus();

    if (!contextStatus.ok) {
        printContextStatusError(contextStatus);
        process.exitCode = 1;
        return {
            changed: false,
            updatedFiles: [],
            incomplete: contextStatus.reason === "incomplete",
            initialized: contextStatus.reason !== "not-initialized",
        };
    }

    const scanData = buildProjectScanData();
    const content = generateProjectMdContent(scanData);
    const taskWarnings = getTaskConsistencyWarnings();

    if (mode === "check") {
        const projectUpdate = getProjectMdUpdate(content);
        const systemOverviewUpdate = getSystemOverviewUpdate();
        const update = combineCheckUpdates(
            projectUpdate,
            systemOverviewUpdate,
            taskWarnings,
        );
        const result = createScanResult(update, scanData, [], taskWarnings);

        printCheckResult(update);
        printWarnings(taskWarnings);

        if (update.changed) {
            process.exitCode = 1;
        }

        return result;
    }

    const indexUpdate = updateProjectIndexSafe();
    const systemOverviewUpdate = updateSystemOverview(
        generateSystemOverviewContent(),
    );
    const update = updateProjectMd(content);
    const updatedFiles = [
        ...(update.changed && !update.skipped ? [CONTEXT_PROJECT_MD_PATH] : []),
        ...getUpdatedIndexFiles(indexUpdate),
        ...(systemOverviewUpdate.changed ? [CONTEXT_SYSTEM_OVERVIEW_PATH] : []),
    ];
    const result = createScanResult(
        {
            ...update,
            changed: update.changed || systemOverviewUpdate.changed,
        },
        scanData,
        updatedFiles,
        taskWarnings,
    );
    result.index = indexUpdate;
    result.systemOverview = systemOverviewUpdate;

    if (!result.changed) {
        if (mode === "auto") {
            printAutoScanResult(result);
            return result;
        }

        printDefaultScanResult(result);
        return result;
    }

    if (update.skipped) {
        printSkippedUpdateResult();
        process.exitCode = 1;
        return result;
    }

    if (mode === "auto") {
        printAutoScanResult(result);
        return result;
    }

    printDefaultScanResult(result);

    return result;
}
