import fs from "node:fs";
import path from "node:path";
import { detectEntryPoints } from "./detectors/entry-points.js";
import { buildOverview } from "./detectors/overview.js";
import { detectProjectType } from "./detectors/project-type.js";
import {
    detectReusableSystem,
    detectSharedUi,
    detectUtilityDirs,
} from "./detectors/reusable-system.js";
import { detectRiskAreas } from "./detectors/risk-areas.js";
import {
    CONTEXT_AI_PATH,
    CONTEXT_DIR,
    CONTEXT_INDEX_ENTRYPOINTS_PATH,
    CONTEXT_INDEX_FILE_GROUPS_PATH,
    CONTEXT_INDEX_FILES_PATH,
    CONTEXT_INDEX_SUMMARY_PATH,
    CONTEXT_INDEX_SYMBOLS_PATH,
    CONTEXT_PROJECT_MD_PATH,
    CONTEXT_SYSTEM_OVERVIEW_PATH,
    CONTEXT_TASKS_PATH,
} from "./constants.js";
import { getContextStatus } from "./context.js";
import {
    getClosestStructurePath,
    detectStructure,
    getStructureDescription,
} from "./detectors/structure.js";
import { exists, isDirectory, readJson, statSafe } from "./fs-utils.js";
import { appendLoopEvent } from "../loop/store.js";
import { detectPackageMetadata, detectTechStack } from "./package-utils.js";
import { buildTaskMap, updateProjectIndex } from "./indexers/project-index.js";
import {
    generateSystemOverviewContent,
    getSystemOverviewUpdate,
    updateSystemOverview,
} from "./system-overview.js";
import { getTaskConsistencyWarnings } from "./task-files.js";
import { getProjectMdUpdate, updateProjectMd } from "./writers/project-md.js";

function formatDescriptiveList(items) {
    return items.map((item) =>
        item.description ? `- ${item.label} -> ${item.description}` : `- ${item.label}`,
    );
}

function extractReferencedDirectories(lines) {
    const referencedDirs = new Set();
    const pathMatches = lines.flatMap(
        (line) => line.match(/(?:\.[A-Za-z0-9_-]+|[A-Za-z0-9_-]+)(?:\/[A-Za-z0-9_.-]+)+\/?/g) || [],
    );

    for (const match of pathMatches) {
        const normalized = match.replace(/`/g, "").replace(/\/+$/, "");
        const mappedStructurePath = getClosestStructurePath(normalized);

        if (mappedStructurePath && exists(mappedStructurePath)) {
            referencedDirs.add(mappedStructurePath);
            continue;
        }

        if (isDirectory(normalized)) {
            referencedDirs.add(normalized);
            continue;
        }

        const lastSlashIndex = normalized.lastIndexOf("/");
        if (lastSlashIndex === -1) {
            continue;
        }

        const parentDir = normalized.slice(0, lastSlashIndex);
        const mappedParentPath = getClosestStructurePath(parentDir);

        if (mappedParentPath && exists(mappedParentPath)) {
            referencedDirs.add(mappedParentPath);
            continue;
        }

        if (parentDir && isDirectory(parentDir)) {
            referencedDirs.add(parentDir);
        }
    }

    return [...referencedDirs];
}

function mergeStructureWithReferences(structure, reusableSystem, risks) {
    const structureByLabel = new Map(structure.map((item) => [item.label, item]));
    const referencedDirs = extractReferencedDirectories([
        ...reusableSystem.sections.flatMap((section) => section.items),
        ...risks,
    ]);

    for (const dir of referencedDirs) {
        const label = `${dir}/`;

        if (structureByLabel.has(label)) {
            continue;
        }

        structureByLabel.set(label, {
            label,
            description:
                getStructureDescription(dir) ||
                "referenced project directory with shared implementation significance",
        });
    }

    return [...structureByLabel.values()];
}

function buildProjectScanData() {
    const projectType = detectProjectType();
    const techStack = detectTechStack(projectType);
    const packageMetadata = detectPackageMetadata();
    const sharedUi = detectSharedUi();
    const utilityDirs = detectUtilityDirs();
    const reusableSystem = detectReusableSystem(
        projectType,
        sharedUi,
        utilityDirs,
    );
    const structure = detectStructure(projectType);
    const risks = detectRiskAreas(projectType, structure, sharedUi);
    const mergedStructure = mergeStructureWithReferences(
        structure,
        reusableSystem,
        risks,
    );
    const entryPoints = detectEntryPoints(projectType);
    const overview = buildOverview(projectType, techStack);

    return {
        projectType,
        techStack,
        packageMetadata,
        reusableSystem,
        risks,
        mergedStructure,
        entryPoints,
        overview,
    };
}

export function generateProjectMdContent(scanData = buildProjectScanData()) {
    const {
        projectType,
        techStack,
        packageMetadata,
        reusableSystem,
        risks,
        mergedStructure,
        entryPoints,
        overview,
    } = scanData;

    const lines = [
        "This section is automatically generated by `repo-context-kit scan`.",
        "Do not edit manually.",
        "",
        "## Project Type",
        `- ${projectType}`,
        "",
        "## Overview",
        ...overview,
        "",
        "## Tech Stack",
    ];

    if (techStack.length === 0) {
        lines.push("- Not clearly detected");
    } else {
        lines.push(...techStack.map((item) => `- ${item}`));
    }

    lines.push("", "## Package Metadata");
    if (!packageMetadata) {
        lines.push("- package.json not found");
    } else {
        if (packageMetadata.name) {
            lines.push(`- name: ${packageMetadata.name}`);
        }
        if (packageMetadata.version) {
            lines.push(`- version: ${packageMetadata.version}`);
        }
        if (packageMetadata.type) {
            lines.push(`- module type: ${packageMetadata.type}`);
        }
        if (packageMetadata.license) {
            lines.push(`- license: ${packageMetadata.license}`);
        }
        if (packageMetadata.packageManager) {
            lines.push(`- package manager: ${packageMetadata.packageManager}`);
        }

        if (packageMetadata.bin.length > 0) {
            lines.push("- bin:");
            for (const binEntry of packageMetadata.bin) {
                lines.push(`  - ${binEntry.name} -> ${binEntry.path}`);
            }
        }

        if (packageMetadata.scripts.length > 0) {
            lines.push("- scripts:");
            for (const script of packageMetadata.scripts) {
                lines.push(`  - ${script.name}: ${script.command}`);
            }
        }
    }

    lines.push(
        "",
        "## AI Development Notes",
        "- This is an npm CLI tool",
        "- Entry point: bin/cli.js",
        "- Template files are copied into user projects during init",
        "- template/ paths are runtime template sources; do not rewrite them as generated output paths",
        `- .claude/skills and ${CONTEXT_DIR}/tests are generated in user projects when present in the template`,
        "- Do not modify generated files unless explicitly required",
        "- Preserve package manager (npm/yarn/pnpm)",
        "- Follow existing file structure when adding new features",
    );

    lines.push("", "## Structure Overview");
    if (mergedStructure.length === 0) {
        lines.push("- No standard project structure detected");
    } else {
        lines.push(...formatDescriptiveList(mergedStructure));
    }

    lines.push("", "## Entry Points");
    if (entryPoints.length === 0) {
        lines.push("- No common entry files detected");
    } else {
        lines.push(...formatDescriptiveList(entryPoints));
    }

    lines.push("", "## Reusable System");
    for (const section of reusableSystem.sections) {
        lines.push(`### ${section.title}`);
        lines.push(...section.items.map((item) => `- ${item}`));
        lines.push("");
    }

    if (lines[lines.length - 1] === "") {
        lines.pop();
    }

    lines.push("", "## Risk Areas");
    if (risks.length === 0) {
        lines.push("- No obvious shared-risk areas detected");
    } else {
        lines.push(...risks.map((risk) => `- ${risk}`));
    }

    lines.push(
        "",
        "## Project Notes",
        "- Reuse existing structures before creating new ones",
        "- Treat shared modules cautiously and preserve backward compatibility",
        "- Keep changes minimal and localized unless the task explicitly requires broader refactoring",
    );

    return lines.join("\n");
}

function getUpdatedIndexFiles(indexUpdate) {
    const updatedFiles = [];

    if (indexUpdate.aiChanged) {
        updatedFiles.push(CONTEXT_AI_PATH);
    }
    if (indexUpdate.filesChanged) {
        updatedFiles.push(CONTEXT_INDEX_FILES_PATH);
    }
    if (indexUpdate.symbolsChanged) {
        updatedFiles.push(CONTEXT_INDEX_SYMBOLS_PATH);
    }
    if (indexUpdate.fileGroupsChanged) {
        updatedFiles.push(CONTEXT_INDEX_FILE_GROUPS_PATH);
    }
    if (indexUpdate.entrypointsChanged) {
        updatedFiles.push(CONTEXT_INDEX_ENTRYPOINTS_PATH);
    }
    if (indexUpdate.summaryChanged) {
        updatedFiles.push(CONTEXT_INDEX_SUMMARY_PATH);
    }
    if (indexUpdate.tasksChanged) {
        updatedFiles.push(CONTEXT_TASKS_PATH);
    }

    return updatedFiles;
}

function createScanResult(update, scanData, updatedFiles = [], warnings = []) {
    return {
        changed: update.changed,
        updatedFiles,
        warnings,
        project: {
            type: scanData.projectType,
            entryPoints: scanData.entryPoints.map((entryPoint) => entryPoint.label),
        },
    };
}

function printChanges(updatedFiles) {
    console.log("Changes:");

    if (updatedFiles.length === 0) {
        console.log("* No changes");
        return;
    }

    for (const filePath of updatedFiles) {
        console.log(`* Updated ${filePath}`);
    }
}

function printDefaultScanResult(result) {
    console.log("OK Project scan completed");
    console.log("");
    printChanges(result.updatedFiles);
    console.log("");
    console.log("Summary:");
    console.log(`* Project type: ${result.project.type}`);
    console.log(
        `* Entry points: ${
            result.project.entryPoints.length > 0
                ? result.project.entryPoints.join(", ")
                : "None detected"
        }`,
    );
    printWarnings(result.warnings);
}

function printAutoScanResult(result) {
    console.log("OK Project scan completed");
    console.log("");
    printChanges(result.updatedFiles);
    console.log("");
    console.log("Mode:");
    console.log("* auto");
    printWarnings(result.warnings);
}

function printWarnings(warnings = []) {
    if (warnings.length === 0) {
        return;
    }

    console.log("");
    console.log("Warnings:");
    for (const warning of warnings) {
        console.log(`* ${warning}`);
    }
}

const PLAN_OUTPUTS = [
    CONTEXT_PROJECT_MD_PATH,
    CONTEXT_SYSTEM_OVERVIEW_PATH,
    CONTEXT_AI_PATH,
    CONTEXT_INDEX_FILES_PATH,
    CONTEXT_INDEX_SYMBOLS_PATH,
    CONTEXT_INDEX_FILE_GROUPS_PATH,
    CONTEXT_INDEX_ENTRYPOINTS_PATH,
    CONTEXT_INDEX_SUMMARY_PATH,
    CONTEXT_TASKS_PATH,
];

const PLAN_SKIPPED_DIRS = new Set([
    ".git",
    ".aidw",
    "node_modules",
    ".changeset",
    ".next",
    "dist",
    "build",
    "coverage",
]);

function listProjectFiles(dir = process.cwd(), results = []) {
    let entries;
    try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
        return results;
    }

    for (const entry of entries) {
        if (entry.isDirectory()) {
            if (!PLAN_SKIPPED_DIRS.has(entry.name)) {
                listProjectFiles(path.join(dir, entry.name), results);
            }
            continue;
        }

        if (entry.isFile()) {
            results.push(
                path
                    .relative(process.cwd(), path.join(dir, entry.name))
                    .replaceAll(path.sep, "/"),
            );
        }
    }

    return results;
}

function getLatestProjectMtimeMs() {
    const files = listProjectFiles();
    let latest = 0;
    for (const filePath of files) {
        const stat = statSafe(filePath);
        if (stat && stat.mtimeMs > latest) {
            latest = stat.mtimeMs;
        }
    }
    return latest || null;
}

function hasTaskMetadataNewerThan(baselineMs) {
    const registryStat = statSafe("task/task.md");
    if (registryStat && registryStat.mtimeMs > baselineMs) {
        return true;
    }

    try {
        const dirStat = statSafe("task");
        if (!dirStat || !dirStat.isDirectory()) {
            return false;
        }
    } catch {
        return false;
    }

    const entries = fs.readdirSync(path.resolve(process.cwd(), "task"), { withFileTypes: true });
    for (const entry of entries) {
        if (!entry.isFile() || !entry.name.toLowerCase().endsWith(".md")) {
            continue;
        }
        if (entry.name.toLowerCase() === "task.md") {
            continue;
        }
        const stat = statSafe(`task/${entry.name}`);
        if (stat && stat.mtimeMs > baselineMs) {
            return true;
        }
    }

    return false;
}

function detectFileListDiff() {
    const current = new Set(listProjectFiles());
    const previous = new Set(
        (readJson(CONTEXT_INDEX_FILES_PATH) ?? [])
            .map((entry) => String(entry?.path ?? "").trim())
            .filter(Boolean),
    );
    const added = [];
    const removed = [];
    for (const filePath of current) {
        if (!previous.has(filePath)) {
            added.push(filePath);
        }
    }
    for (const filePath of previous) {
        if (!current.has(filePath)) {
            removed.push(filePath);
        }
    }
    return {
        added,
        removed,
        changed: added.length > 0 || removed.length > 0,
    };
}

function printScanPlan({ willUpdate = [], reasons = [] }) {
    console.log("Scan Plan");
    console.log("");
    console.log("Will update:");
    if (willUpdate.length === 0) {
        console.log("- (none)");
    } else {
        for (const filePath of willUpdate) {
            console.log(`- ${filePath}`);
        }
    }
    console.log("");
    console.log("Reasons:");
    if (reasons.length === 0) {
        console.log("- (none)");
    } else {
        for (const reason of reasons) {
            console.log(`- ${reason}`);
        }
    }
    console.log("");
    console.log("No files were written.");
}

function combineCheckUpdates(projectUpdate, systemOverviewUpdate, warnings) {
    const taskMapChanged =
        JSON.stringify(readJson(CONTEXT_TASKS_PATH) ?? null) !==
        JSON.stringify(buildTaskMap());

    return {
        changed:
            projectUpdate.changed ||
            systemOverviewUpdate.changed ||
            taskMapChanged ||
            warnings.length > 0,
        skipped: projectUpdate.skipped,
        projectChanged: projectUpdate.changed,
        systemOverviewChanged: systemOverviewUpdate.changed,
        taskMapChanged,
        taskRegistryChanged: warnings.length > 0,
    };
}

export function computeScanCheckState() {
    const scanData = buildProjectScanData();
    const content = generateProjectMdContent(scanData);
    const taskWarnings = getTaskConsistencyWarnings();
    const projectUpdate = getProjectMdUpdate(content);
    const systemOverviewUpdate = getSystemOverviewUpdate();
    const update = combineCheckUpdates(projectUpdate, systemOverviewUpdate, taskWarnings);

    return {
        scanData,
        taskWarnings,
        update,
    };
}

function maybeAppendLearnableScanEvent(event) {
    if (!isDirectory(CONTEXT_DIR)) {
        return null;
    }

    try {
        return appendLoopEvent(event);
    } catch {
        return null;
    }
}

function printCheckResult(update) {
    if (update.skipped) {
        console.log("ERROR Project context cannot be checked");
        console.log("");
        console.log("Reason:");
        console.log(`* AUTO-GENERATED markers not found in ${CONTEXT_PROJECT_MD_PATH}`);
        console.log("");
        console.log("Next:");
        console.log("* Run 'repo-context-kit scan' to regenerate.");
        return;
    }

    if (!update.changed) {
        console.log("OK Project context is up to date");
        console.log("");
        console.log("Checked:");
        console.log(`* ${CONTEXT_PROJECT_MD_PATH} AUTO-GENERATED section`);
        console.log(`* ${CONTEXT_SYSTEM_OVERVIEW_PATH}`);
        return;
    }

    console.log("ERROR Project context is outdated");
    console.log("");
    console.log("Changes:");
    if (update.projectChanged) {
        console.log(`* ${CONTEXT_PROJECT_MD_PATH} generated section is out of date`);
    }
    if (update.systemOverviewChanged) {
        console.log(`* ${CONTEXT_SYSTEM_OVERVIEW_PATH} is missing or out of date`);
    }
    if (update.taskMapChanged) {
        console.log(`* ${CONTEXT_TASKS_PATH} is missing or out of date`);
    }
    if (update.taskRegistryChanged) {
        console.log("* task registry and task files are inconsistent");
    }
    console.log("");
    console.log("Next:");
    console.log("* Run 'repo-context-kit scan' to update.");
}

function printSkippedUpdateResult() {
    console.log("ERROR Project scan cannot update project context");
    console.log("");
    console.log("Reason:");
    console.log(`* AUTO-GENERATED markers not found in ${CONTEXT_PROJECT_MD_PATH}`);
    console.log("");
    console.log("Next:");
    console.log(`* Add AUTO-GENERATED markers or regenerate ${CONTEXT_PROJECT_MD_PATH}.`);
}

function printContextStatusError(status) {
    if (status.reason === "not-initialized") {
        console.log("ERROR Project not initialized");
        console.log(`Missing: ${CONTEXT_DIR}/`);
        console.log("Run: repo-context-kit init");
        return;
    }

    console.log("ERROR Project context is incomplete");
    console.log("Run: repo-context-kit scan --auto");
}

function updateProjectIndexSafe() {
    try {
        return updateProjectIndex();
    } catch (error) {
        console.warn(`Warning: Project index generation failed: ${error.message}`);
        return {
            aiChanged: false,
            filesChanged: false,
            symbolsChanged: false,
            fileGroupsChanged: false,
            entrypointsChanged: false,
            summaryChanged: false,
            tasksChanged: false,
        };
    }
}

export async function runScan(options = {}) {
    const mode = options.mode || "normal";
    const contextStatus = getContextStatus();

    if (mode === "plan") {
        const scanData = buildProjectScanData();
        const content = generateProjectMdContent(scanData);
        const taskWarnings = getTaskConsistencyWarnings();
        const baseline = statSafe(CONTEXT_INDEX_SUMMARY_PATH);
        const baselineMs = baseline ? baseline.mtimeMs : null;
        const latestProjectMs = getLatestProjectMtimeMs();
        const packageStat = statSafe("package.json");
        const packageChanged = baselineMs != null && packageStat && packageStat.mtimeMs > baselineMs;
        const taskChanged = baselineMs != null && hasTaskMetadataNewerThan(baselineMs);
        const fileDiff = exists(CONTEXT_INDEX_FILES_PATH) ? detectFileListDiff() : { changed: true, added: [], removed: [] };
        const scanStale =
            baselineMs == null ||
            (latestProjectMs != null && latestProjectMs > baselineMs) ||
            fileDiff.changed ||
            PLAN_OUTPUTS.some((filePath) => !exists(filePath));

        const projectUpdate = getProjectMdUpdate(content);
        const systemOverviewUpdate = getSystemOverviewUpdate();
        const taskMapChanged =
            JSON.stringify(readJson(CONTEXT_TASKS_PATH) ?? null) !==
            JSON.stringify(buildTaskMap());

        const willUpdateSet = new Set();
        const reasons = [];

        if (!contextStatus.ok) {
            reasons.push(
                contextStatus.reason === "not-initialized"
                    ? "project is not initialized"
                    : "project context is incomplete",
            );
            for (const filePath of PLAN_OUTPUTS) {
                willUpdateSet.add(filePath);
            }
        } else {
            if (projectUpdate.skipped) {
                reasons.push(`AUTO-GENERATED markers missing in ${CONTEXT_PROJECT_MD_PATH}`);
            }
            if (projectUpdate.changed || !exists(CONTEXT_PROJECT_MD_PATH)) {
                willUpdateSet.add(CONTEXT_PROJECT_MD_PATH);
            }
            if (systemOverviewUpdate.changed || !exists(CONTEXT_SYSTEM_OVERVIEW_PATH)) {
                willUpdateSet.add(CONTEXT_SYSTEM_OVERVIEW_PATH);
            }
            if (scanStale) {
                reasons.push("previous scan is stale");
                for (const filePath of [
                    CONTEXT_AI_PATH,
                    CONTEXT_INDEX_FILES_PATH,
                    CONTEXT_INDEX_SYMBOLS_PATH,
                    CONTEXT_INDEX_FILE_GROUPS_PATH,
                    CONTEXT_INDEX_ENTRYPOINTS_PATH,
                    CONTEXT_INDEX_SUMMARY_PATH,
                ]) {
                    willUpdateSet.add(filePath);
                }
            }
            if (packageChanged) {
                reasons.push("package.json changed");
            }
            if (taskChanged) {
                reasons.push("task metadata changed");
            }
            if (fileDiff.changed) {
                reasons.push("new or removed source files detected");
            }
            if (taskMapChanged || scanStale) {
                willUpdateSet.add(CONTEXT_TASKS_PATH);
            }
            if (taskWarnings.length > 0) {
                reasons.push("task registry and task files are inconsistent");
            }
        }

        printScanPlan({
            willUpdate: [...willUpdateSet].filter(Boolean).sort(),
            reasons: [...new Set(reasons)].filter(Boolean),
        });

        return {
            planned: true,
            willUpdate: [...willUpdateSet],
            reasons,
            warnings: taskWarnings,
        };
    }

    if (!contextStatus.ok) {
        printContextStatusError(contextStatus);
        maybeAppendLearnableScanEvent({
            type: "scan_failed",
            ok: false,
            reason: contextStatus.reason,
        });
        process.exitCode = 1;
        return {
            changed: false,
            updatedFiles: [],
            incomplete: contextStatus.reason === "incomplete",
            initialized: contextStatus.reason !== "not-initialized",
        };
    }

    if (mode === "check") {
        const { scanData, taskWarnings, update } = computeScanCheckState();
        const result = createScanResult(update, scanData, [], taskWarnings);

        printCheckResult(update);
        printWarnings(taskWarnings);

        if (update.changed) {
            maybeAppendLearnableScanEvent({
                type: "scan_check_failed",
                ok: false,
                projectChanged: update.projectChanged,
                systemOverviewChanged: update.systemOverviewChanged,
                taskMapChanged: update.taskMapChanged,
                taskRegistryChanged: update.taskRegistryChanged,
                skipped: update.skipped,
                warnings: taskWarnings,
            });
            process.exitCode = 1;
        } else {
            maybeAppendLearnableScanEvent({
                type: "scan_check_passed",
                ok: true,
            });
        }

        return result;
    }

    const scanData = buildProjectScanData();
    const content = generateProjectMdContent(scanData);
    const taskWarnings = getTaskConsistencyWarnings();
    const indexUpdate = updateProjectIndexSafe();
    const systemOverviewUpdate = updateSystemOverview(
        generateSystemOverviewContent(),
    );
    const update = updateProjectMd(content);
    const updatedFiles = [
        ...(update.changed && !update.skipped ? [CONTEXT_PROJECT_MD_PATH] : []),
        ...getUpdatedIndexFiles(indexUpdate),
        ...(systemOverviewUpdate.changed ? [CONTEXT_SYSTEM_OVERVIEW_PATH] : []),
    ];
    const result = createScanResult(
        {
            ...update,
            changed: update.changed || systemOverviewUpdate.changed,
        },
        scanData,
        updatedFiles,
        taskWarnings,
    );
    result.index = indexUpdate;
    result.systemOverview = systemOverviewUpdate;

    if (!result.changed) {
        if (mode === "auto") {
            printAutoScanResult(result);
            return result;
        }

        printDefaultScanResult(result);
        return result;
    }

    if (update.skipped) {
        printSkippedUpdateResult();
        maybeAppendLearnableScanEvent({
            type: "scan_failed",
            ok: false,
            reason: "missing_auto_generated_markers",
        });
        process.exitCode = 1;
        return result;
    }

    if (mode === "auto") {
        printAutoScanResult(result);
        return result;
    }

    printDefaultScanResult(result);

    return result;
}
